repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v5.9.3'
      hooks:
        - id: isort
          args: ["--profile", "black"]
    - repo: https://github.com/psf/black
      rev: 21.8b0
      hooks:
        - id: black
          language_version: python3
    - repo: https://github.com/PyCQA/flake8
      rev: "5.0.4"
      hooks:
        - id: flake8
